Refactor to component to use new token structure and new version of icon
selsa-inube/inubekit-toggle pull request #4
Opened 2024-02-22 23:59 UTC by cmarin001

This pull request details the refactoring of a specific component within our application to align with a new token structure and to incorporate the latest version of our icon library. This initiative aims to enhance the component's design consistency, usability, and maintainability by leveraging updated design tokens and icon assets.

2024-02-23 04:23 UTC, JanuarAsprilla commented
se genera un error porque aun no ha configurado el vite.config.ts
ya que solo se debería de exportar el componente y este debe excluir los componentes y demás elementos que se instalan para su funcionamiento. 

el vite.config.ts deberia verse asi:

![image](https://github.com/selsa-inube/inubekit-toggle/assets/140556686/ba3c5118-9109-453d-a94f-8e59e4dc5874)

2024-02-23 14:30 UTC, JanuarAsprilla approved these changes

2024-02-23 14:30 UTC, JanuarAsprilla commented on vite.config.ts
> +        "styled-components",
no es necesario que este declarado 2 veces

2024-02-23 16:00 UTC, cmarin001 commented on vite.config.ts
> +        "styled-components",
solved

2024-02-23 21:02 UTC, wfercanas requested changes

2024-02-23 21:02 UTC, wfercanas commented on src/Switch/styles.js
> +            bottom: calc((16px - 12px) / 2);
No usemos el export css de styled-components. Para cada propiedad (width, height, bottom) pasemos el callback correspondiente.

2024-02-23 23:37 UTC, cmarin001 commented on src/Switch/index.tsx
solved

2024-02-23 23:39 UTC, cmarin001 commented on src/Switch/stories/Switch.stories.tsx
solved

2024-02-23 23:45 UTC, cmarin001 commented on src/Switch/index.tsx
> -    padding = "s0",
solved

2024-02-23 23:46 UTC, cmarin001 commented on src/Switch/index.tsx
> +              />
![image](https://github.com/selsa-inube/inubekit-toggle/assets/45011420/f3e8a7e4-c383-4c31-b949-605e306943c1)

2024-02-23 23:46 UTC, cmarin001 commented on src/Switch/index.tsx
> +              />
solved

2024-02-23 23:48 UTC, cmarin001 commented on src/Switch/styles.js
according to mockups that isn't accurate
![image](https://github.com/selsa-inube/inubekit-toggle/assets/45011420/80c5142e-cb6e-4de3-a779-f0e9bdecbd97)

2024-02-23 23:51 UTC, cmarin001 commented on src/Switch/styles.js
solved

2024-02-24 00:12 UTC, cmarin001 commented on src/Switch/styles.js
> +            bottom: calc((16px - 12px) / 2);
solved

2024-02-25 05:34 UTC, JanuarAsprilla approved these changes

2024-02-26 17:34 UTC, wfercanas commented on src/Switch/styles.js
Hay que usar el archivo "V2" en figma.

2024-02-26 17:38 UTC, wfercanas commented on src/Switch/index.tsx
> +              />
Aquí hay un par de detalles a tener en cuenta:
1. El icon efectivamente recibe una prop `appearance` y ahí la idea es que pasemos el appearance según el valor de checked en el toggle. Si `checked === true`, hay que pasarle `toggle.on.icon.appearance`. Si `checked === false` hay que pasar `off`.
2. El icon recibe otra prop aparte que es `disabled`. Aquí la relación es directa, porque el toggle le puede pasar su prop `disabled` directo al icon sin necesidad de evaluar algo adicional.

2024-02-26 17:47 UTC, wfercanas requested changes

2024-02-26 17:47 UTC, wfercanas commented on src/Toggle/index.tsx
> +interface IToggleProps {
Dejemos sólo IToggle

2024-02-26 17:47 UTC, wfercanas commented on src/Toggle/styles.js
> +    ${({ $disabled, $size }) =>
Esta función está tocando 2 propiedades css con su return. Defina cada propiedad por separado y cada una, si es necesario, tendrá su callback.

Aquí por ejemplo `transform: translateX(20px)` no necesita callback.

2024-02-26 17:47 UTC, wfercanas commented on src/Toggle/styles.js
> +    ${({ $size }) => `
Primero las propiedades y cada una por aparte define su callback

2024-02-26 17:47 UTC, wfercanas commented on src/Toggle/styles.js
> +  ${({ $size }) => $size && sizes[$size]};
Esto retorna `sizes[$size]` pero en apariencia no está afectando ninguna propiedad CSS. 

Es preferible que use las propiedades `width` y `height` y que en cada callback saque esa propiedad en específico del objeto en `sizes[$size]`

2024-02-26 17:47 UTC, wfercanas commented on src/Toggle/styles.js
> +const StyledContainer = styled.label`
Si esto es un styled.label, puede renombrar el styled-component como `StyledLabel`

2024-02-26 19:34 UTC, cmarin001 commented on src/Toggle/index.tsx
> +interface IToggleProps {
solved

2024-02-26 19:51 UTC, cmarin001 commented on src/Toggle/styles.js
> +    ${({ $size }) => `
solved

2024-02-26 20:04 UTC, cmarin001 commented on src/Toggle/styles.js
> +  ${({ $size }) => $size && sizes[$size]};
solved

2024-02-26 20:07 UTC, cmarin001 commented on src/Toggle/styles.js
> +const StyledContainer = styled.label`
solved

2024-02-26 20:30 UTC, cmarin001 commented on src/Switch/index.tsx
> +              />
solved

2024-02-26 21:00 UTC, cmarin001 commented on src/Switch/styles.js
solved

2024-02-26 21:12 UTC, JanuarAsprilla approved these changes

2024-02-27 15:19 UTC, wfercanas requested changes

2024-02-27 16:31 UTC, cmarin001 commented on vite.config.ts
> +      external: [
solved

2024-02-27 16:41 UTC, cmarin001 commented on src/Toggle/index.tsx
> +          {checked && !disabled ? (
solved

2024-02-27 16:43 UTC, cmarin001 commented on src/Toggle/index.tsx
solved

2024-02-27 16:45 UTC, cmarin001 commented on src/Toggle/styles.js
> +`;
solved

2024-02-27 18:58 UTC, JanuarAsprilla approved these changes

2024-02-27 20:00 UTC, wfercanas commented on src/Toggle/index.tsx
Este error persiste. Si un toggle está on y el disabled pasa a true, el toggle se pone off.
Si después pasa disabled a false, el toggle regresa a on.

El hecho de estar disabled no tiene por qué afectar el value del toggle. Sólo afecta que el usuario no lo puede modificar.

2024-02-27 20:03 UTC, wfercanas requested changes

2024-02-27 20:03 UTC, wfercanas commented on src/Toggle/styles.js
El toggle-border no está quedando gris según se especifica en los tokens. Hay que ver los estilos para ver por qué.
Storybook:
![image](https://github.com/selsa-inube/inubekit-toggle/assets/36939686/dff83a4e-e682-4cff-a155-57fb98fab6dc)
Mockups:
![image](https://github.com/selsa-inube/inubekit-toggle/assets/36939686/da541c50-5955-47b4-9d7f-1d022f0ba6c2)

2024-02-27 20:40 UTC, cmarin001 commented on src/Toggle/styles.js
solved

2024-02-27 21:19 UTC, cmarin001 commented on src/Toggle/index.tsx
solved

2024-02-28 14:36 UTC, JanuarAsprilla approved these changes

2024-02-28 16:17 UTC, wfercanas requested changes

2024-02-28 16:17 UTC, wfercanas commented on src/Toggle/styles.js
Cuando el componente está on y pasa de `disabled === false` a `true`, el toggle (círculo) se está moviendo unos pixeles a la izquierda.
![image](https://github.com/selsa-inube/inubekit-toggle/assets/36939686/84cb7c6c-1b67-49ea-9709-76a81963b051)
![image](https://github.com/selsa-inube/inubekit-toggle/assets/36939686/3f0da49b-ae68-4135-accb-df95907ece84)

2024-02-28 17:30 UTC, cmarin001 commented on src/Toggle/styles.js
solved

2024-02-28 20:34 UTC, JanuarAsprilla approved these changes

2024-03-01 21:40 UTC, wfercanas approved these changes

2024-03-01 21:40 UTC, merged